version: '3'

tasks:
  start:
    cmds:
      - task: start-docker
      - task: start-app
      - task: start-test-server

  start-docker:
    cmds:
      - docker-compose up -d

  start-app:
    cmds:
      - go run cmd/musicAPI/main.go

  start-test-server:
    cmds:
      - go run cmd/testserver/main.go

  stop:
    cmds:
      - docker-compose down
  dockerrun:
      - docker run --name musicAPI -p 5432:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -d ubuntu/postgres
  createdb:
    - docker exec -it musicAPI createdb --username=user --owner=user musicAPI