
###
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "group": "T",
  "song": "T"
}

> {%
client.test("Song added successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
GET http://localhost:8080/songs/couplets?group=Theaada%20Bdedaays&song="Heyddddddd%20Jhdaaaaue"&page=0&limit=7

> {%
client.test("Couplets retrieved successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.couplets !== undefined, "Couplets are not present in response");
});
%}

###
PATCH http://localhost:8080/songs/edit
Content-Type: application/json

{
  "title": { "group": "T", "song": "T"},
  "info": {
    "releaseDate": "11.10.2006",
    "text": "pisya\\n\\npopa\\n\\npopa\\n\\nj\\n\\nsdas\\n\\nasadasd",
    "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
  }
}

> {%
client.test("Song edited successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
DELETE http://localhost:8080/songs/delete
Content-Type: application/json

{
  "group": "The Beatles",
  "song": "Hey Jude"
}

> {%
client.test("Song deleted successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
GET http://localhost:8080/songs/filter-by-group-and-date?page=1&limit=100
Content-Type: application/json

{
  "group": [],
  "period":
  {
    "start": "12.10.2000",
    "end": "12.10.2020"
  }
}

> {%
client.test("Song edited successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}