
###
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "group": "T",
  "song": "TTeessst"
}

> {%
client.test("Song added successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
POST http://localhost:8080/songs/couplets?limit=2
Content-Type: application/json

{
  "group": "T",
  "song": "TTeessst"
}

> {%
client.test("Couplets retrieved successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.couplets !== undefined, "Couplets are not present in response");
});
%}

###
PATCH http://localhost:8080/songs/edit
Content-Type: application/json

{
  "title": { "group": "T1", "song": "T"},
  "info": {
    "releaseDate": "11.10.0909",
    "text": "p\\n\\no\\n\\np\\n\\nj\\n\\ns\\n\\na",
    "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
  }
}

> {%
client.test("Song edited successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
DELETE http://localhost:8080/songs/delete
Content-Type: application/json

{
  "group": "T1",
  "song": "T"
}

> {%
client.test("Song deleted successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
POST http://localhost:8080/songs/filter-by-group-and-date?page=1&limit=2
Content-Type: application/json

{
  "group": 1,
  "period":
  {
    "end": "12.10.2024"
  }
}

> {%
client.test("Song edited successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}