
###
POST http://localhost:8080/songs/add
Content-Type: application/json

{
  "group": "The Beys",
  "song": "Hey Jhue"
}

> {%
client.test("Song added successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
GET http://localhost:8080/songs/couplets?group=The%20Beatles&song=Hey%20Jude&page=1&limit=10

> {%
client.test("Couplets retrieved successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.couplets !== undefined, "Couplets are not present in response");
});
%}

###
PATCH http://localhost:8080/songs/edit
Content-Type: application/json

{
  "title": { "group": "The Beys", "song": "Hey Jhue"},
  "info": {
    "releaseDate": "11.010.2006",
    "text": "pisya\\n\\npopa",
    "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
  }
}

> {%
client.test("Song edited successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###
DELETE http://localhost:8080/songs/delete
Content-Type: application/json

{
  "group": "The Beatles",
  "song": "Hey Jude"
}

> {%
client.test("Song deleted successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}
